### ISSUE TITLE
[Question] Scripts for spawn new pod instance in kubernetes?

### ISSUE THREAD

**Issue by TommyLike** [praiskup/resalloc#109]
Is there any script for spawn/manage/delete new pod instance in kubernetes?

**Comment by praiskup** [comment]
Thank you for the question, @TommyLike.

Such a script was not prepared yet by us, please let us know if you plan
to work on one!

Resalloc is currently used by Copr for starting VMs in various
environments, but not yet for starting containers.  The thing is that Copr
builds RPMs, and for building RPMs you need to install other RPMs on
demand (build dependencies, BuildRequires).  Installing RPMs can only be
done root user - and it is a rare situation to have root in kubernetes
containers.

**Comment by TommyLike** [comment]
> Thank you for the question, @TommyLike.
> 
> Such a script was not prepared yet by us, please let us know if you plan to work on one!
> 
> Resalloc is currently used by Copr for starting VMs in various environments, but not yet for starting containers. The thing is that Copr builds RPMs, and for building RPMs you need to install other RPMs on demand (build dependencies, BuildRequires). Installing RPMs can only be done root user - and it is a rare situation to have root in kubernetes containers.

Thanks @praiskup, I am planning to support it, although there would be some security concerns, the container would be more lightweight and faster.

**Comment by praiskup** [comment]
Ok, thank you for the info - once you have the script handy - it would be nice if we could e.g. link them in our documentation as examples.

**Comment by FrostyX** [comment]
> it would be nice if we could e.g. link them in our documentation as examples.

We should also mention these at the same place

- https://github.com/praiskup/resalloc-openstack
- https://github.com/praiskup/resalloc-aws

**Comment by TommyLike** [comment]
@FrostyX @praiskup Here is the first version to spawn&delete new resource in kubernetes: https://github.com/TommyLike/resalloc-kubernetes
Also I have a question, Is there any logic regarding existing resource menagement? For instance, when resalloc server restarts or shuting down, how to handle the allocated resource? Thanks

**Comment by TommyLike** [comment]
> https://github.com/TommyLike/resalloc-kubernetes

Thanks for your reply @praiskup ,
Let me be more specific:
1. how to handle the allocated resource correctly when resalloc is signaled to shutdown? delete/release command will be triggered?
2. how to collect existing resource for using when resalloc is restarted?
These two are normal cases especially when we are deploying in kubernetes.  :)

**Comment by praiskup** [comment]
> 1. how to handle the allocated resource correctly when resalloc is signaled to
>    shutdown? delete/release command will be triggered?

When shutting down, nothing is really happening.  We may try to come up
with some solution, though typically it is solved after restart.

This is handled by commit 4dd636bf00d5e88201765436c7e1d00cd5f656ff -
STARTING/DELETING/RELEASING machines are simply removed and we
start new resources instead (it would be hard to continue on the booting
process).

> 2. how to collect existing resource for using when resalloc is
>    restarted?  These two are normal cases especially when we are
>    deploying in kubernetes. :)

The database resalloc is connected to persists (postgresql/sqlite).  So
the machines that are started stay in the DB and can be normally reused.
