### ISSUE TITLE
Some ticket not closed by backend

### ISSUE THREAD

**Issue by pkking** [praiskup/resalloc#117]
This week we start some builds( about 2000 build) maybe a bit large.
After the weekend we noticed that some tickets were not closed(no idea why)
which cause new vm ticket can't be alloced.

For a workaround i close some ticket manually using `resalloc ticket-close <id>`

Im still digging into to find the root cause, any suggestions appreciated :P

**Comment by praiskup** [comment]
This typically doesn't happen.  Seems like the background worker was killed and it did not close the ticket?  The answer might or might not be in worker.log, depending if it was killed by OOM or otherwise.

**Comment by praiskup** [comment]
Huh, now I realized after the PTO that this one si really old.  Likely non-issue.  Sorry for the long delay.

**Comment by praiskup** [comment]
Note there's the backend/run/copr-backend-unknown-resalloc-tickets.py script that might help to identify the dangling tickets (we have sometimes such tickets, but they are typically taken manually for debugging purposes).

**Comment by praiskup** [comment]
Ah!  This should have been reported against fedora-copr/copr.
