### ISSUE TITLE
on demand resources

### ISSUE THREAD

**Issue by praiskup** [praiskup/resalloc#24]
Sometimes it would be useful to have pool which doesn't preallocate resources in advance because those wouldn't be used for a long time. It would be better if we started those resources on demand, when ticket requesting that comes.

**Comment by pkking** [comment]
Sorry for reopen this, these day im trying to use resalloc to alloc pod, which is pretty fast to alloc/release, but if the max_prealloc is zero, the pool will not alloc any resouce anymore, it sounds unreasonable.

**Comment by praiskup** [comment]
Thank you for the update.  I suppose we'll have to implement yet another option on top of those we already have.  Something like `allocate_on_demand: true`.
