### ISSUE TITLE
Config option hostname does nothing, it should be host

### ISSUE THREAD

**Issue by FrostyX** [praiskup/resalloc#46]
The default `config/server.yaml` suggests to change `hostname` variable to make xmlrpc server listen on some other address. This config option does nothing though, `resalloc` reads `host` from the config instead.

I would send a PR but I am not sure whether we want to fix the documentation or the code.

**Comment by praiskup** [comment]
Good catch, thanks for the report.

> I would send a PR but I am not sure whether we want to fix the documentation or the code.

Pick what you prefer.  At this moment we still can afford changing the
configuration option name (if we update NEWS file).
