### ISSUE TITLE
Show resource DATA (e.g. IP address if we talk about VMs)

### ISSUE THREAD

**Issue by FrostyX** [praiskup/resalloc#50]
I think it would be useful if `resalloc-maint resource-list` printed also an IP address for each resource. Or alternatively, if we are afraid to get the output too verbose or complicated (which thanks to `tags`, it IMHO is), I think it would be great to introduce something like `resalloc-maint resource-info <id>` for displaying everything we know about the resource.

**Comment by praiskup** [comment]
I agree.  I thought that we could get a "web-ui" sooner with all the necessary info about tickets/resources...   But yeah ...  now you have to look into hooks/ directory, find the allocation log file and read the IP there ... which isn't convenient.

**Comment by praiskup** [comment]
Note that I use this for some time:

    resalloc-maint foreach-resource --command 'echo {name} - {data_utf8}'
