### ISSUE TITLE
Delete all resources

### ISSUE THREAD

**Issue by FrostyX** [praiskup/resalloc#51]
I find myself occasionally deleting all resources on copr-be-dev. You typically don't want to do this on a production server but on dev, it happens that you have broken all builders and they need to be respawned. In such scenario, I do

```
[root@copr-be-dev ~][STG]# su resalloc
bash-5.0$ resalloc-maint resource-list
7282 - aws_x86_64_normal_dev_00007282_20201002_195313 ...
7283 - aws_x86_64_normal_dev_00007283_20201002_195314 ...
7278 - aws_aarch64_normal_dev_00007278_20201002_195012 ...
7284 - aws_x86_64_normal_dev_00007284_20201002_195334 ...
7281 - aws_x86_64_normal_dev_00007281_20201002_195312 ...
7279 - aws_x86_64_normal_dev_00007279_20201002_195309 ...
7280 - aws_x86_64_normal_dev_00007280_20201002_195310 ...
7270 - aws_aarch64_normal_dev_00007270_20201002_193005 ...

bash-5.0$ resalloc-maint resource-delete \
    7282 7283 7278 7284 7281 7279 7280 7270
```

I could probably write a small bash script doing this, but I think it would be nicer to have a possibility to do something like this

    resalloc-maint resource-delete all

and maybe even

    resalloc-maint resource-delete unused

Or whatever syntax you would prefer. Another possibility would be to add `--tag`, `--pool`, `--status` to delete resources by those values - which would IMHO be really cool but overkill.

What do you think?

**Comment by praiskup** [comment]
+1 to all your proposals :-)

**Comment by praiskup** [comment]
The lame way to do this:

    resalloc-maint resource-delete $(resalloc-maint resource-list | sort -n | grep releases=0 | grep ticket=NULL | cut -d' ' -f1)
