### ISSUE TITLE
RFE: Connect to a resource

### ISSUE THREAD

**Issue by FrostyX** [praiskup/resalloc#73]
It would be nice to have something like

```
resalloc-maint resource-ssh <resource-id>
```

Alternatively `resource-shell`, `resource-connect`, or just `resalloc-maint ssh`, ...

**Comment by praiskup** [comment]
Resource is resource, not necessarily a VM.  It can be volume, image, or anything "expensive"

**Comment by praiskup** [comment]
In extreme example it can be "a person" who needs to come and resolve the ticket :-)

**Comment by FrostyX** [comment]
Makes sense :-)
In that case, I guess we should be able to somehow distinguish between such resources and know which of them are ssh-able. And we can add the command simply as `resalloc-maint ssh ...` that would accept such resource IDs (and fail for others) and possibly accept other ssh-able things in the future (but I doubt there will be some)

But feel free to close as INVALID. I am planning to implement #50 which will solve my biggest annoyance with resalloc anyway :-)

**Comment by praiskup** [comment]
> somehow distinguish

This is up to the resalloc admin/resalloc user, what they consider the stored DATA mean (be that IP address, or uuid of some cloud resource).  Or json, or ...

Perhaps one day we can implement some more logic behind resource semantics, but currently this is just KISS.

> implement #50 

+1
