### ISSUE TITLE
Configurable command to introspect the non-tracked resources, and automatic removal

### ISSUE THREAD

**Issue by praiskup** [praiskup/resalloc#88]
For various reasons, we sometimes end-up with still running resources (or at least wasting the quota) while reaslloc considers them non-existing (SSH connection fails, resource is seemingly deleted, etc..).

It would be good to have a new option like `cmd_introspect`.  This would be a shell command that would list all the instances in the pool regardless of the current state of the database (e.g. using `virsh list --all` for hypervisors)  Using this list, we could execute the `cmd_delete` the normal way for all the existing resources not being in the database.  This should happen:

1. as a first action right after the `resalloc` service start (to cleanup the leftovers as soon as possible)
2. periodically, say each 15 minutes

**Comment by praiskup** [comment]
I installed today a new script on copr-be-dev:
```
/var/lib/resallocserver/provision/libvirt-list  --connection qemu+ssh://copr@vmhost-x86-copr03.rdu-cc.fedoraproject.org/system --pool copr_hv_x86_64_03_dev
```

This script is able to list all (even stopped and undefined) LibVirt domains that have some leftovers on the system.  The returned list of domains can be compared with the resources in Resalloc DB -> and if there's something "more", it should be removed (normally, via `cmd_delete`).

**Comment by FrostyX** [comment]
I made two changes to the `libvirt-list` script:

1. If `--connection` is not specified, the script can guess it based on the pool ID (same as `libvirt-new`)
2. The pool ID can be specified via `--pool` or via environment variable (that is how other scripts called from resalloc take their input)

The script can be now called as

```
$ RESALLOC_POOL_ID=copr_hv_x86_64_03_dev /var/lib/resallocserver/provision/libvirt-list  
copr_hv_x86_64_03_dev_00106051_20220528_075809
```
